# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'CoreNotes' do

end

target 'CoreNotesTests' do
pod 'Quick', '~> 0.8.0'
pod 'Nimble', '3.0.0'

end

target 'CoreNotesUITests' do

end

target 'CoreNotesWatch' do

end

target 'CoreNotesWatch Extension' do

end

